/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ServerView;

/**
 *
 * @author nacho
 */
public class ServerWindow extends javax.swing.JFrame {

    /**
     * Creates new form ServerWindow
     */
    public ServerWindow() {
        initComponents();
        this.setSize(935, 624);
        this.CantPlayersSpinBox.setValue(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CantPlayersSpinBox = new javax.swing.JSpinner();
        CantPlayersLabel = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServerLogTextArea = new javax.swing.JTextArea();
        MonopolyLabel = new javax.swing.JLabel();
        BackgroundPanel = new javax.swing.JPanel();
        StartGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(206, 230, 208));
        getContentPane().setLayout(null);

        CantPlayersSpinBox.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(CantPlayersSpinBox);
        CantPlayersSpinBox.setBounds(290, 510, 60, 40);

        CantPlayersLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        CantPlayersLabel.setText("Enter party's size: ");
        getContentPane().add(CantPlayersLabel);
        CantPlayersLabel.setBounds(20, 500, 280, 50);

        ConfirmButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        ConfirmButton.setText("Confirm");
        getContentPane().add(ConfirmButton);
        ConfirmButton.setBounds(370, 510, 130, 40);

        ServerLogTextArea.setBackground(new java.awt.Color(206, 230, 208));
        ServerLogTextArea.setColumns(20);
        ServerLogTextArea.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        ServerLogTextArea.setRows(5);
        jScrollPane1.setViewportView(ServerLogTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 100, 820, 390);

        MonopolyLabel.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        MonopolyLabel.setText("Monopoly");
        getContentPane().add(MonopolyLabel);
        MonopolyLabel.setBounds(340, 20, 220, 50);

        BackgroundPanel.setBackground(new java.awt.Color(164, 208, 167));
        BackgroundPanel.setLayout(null);

        StartGameButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        StartGameButton.setText("Start Game");
        BackgroundPanel.add(StartGameButton);
        StartGameButton.setBounds(710, 510, 150, 40);

        getContentPane().add(BackgroundPanel);
        BackgroundPanel.setBounds(0, 0, 960, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel CantPlayersLabel;
    public javax.swing.JSpinner CantPlayersSpinBox;
    public javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel MonopolyLabel;
    public javax.swing.JTextArea ServerLogTextArea;
    public javax.swing.JButton StartGameButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
