/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ClientView;

/**
 *
 * @author nacho
 */
public class MortgageView extends javax.swing.JFrame {

    /**
     * Creates new form MortgageView
     */
    public MortgageView() {
        initComponents();
        setSize(550,320);

    }
    
    public void setPropertiesComboBox(String[] properties){
        this.PropertiesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(properties));
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PropertiesComboBox = new javax.swing.JComboBox<>();
        Unmortgage = new javax.swing.JButton();
        MortgageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(164, 208, 167));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mortgage");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 10, 140, 50);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Property");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 70, 90, 30);

        PropertiesComboBox.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        PropertiesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(PropertiesComboBox);
        PropertiesComboBox.setBounds(160, 110, 210, 40);

        Unmortgage.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Unmortgage.setForeground(new java.awt.Color(0, 0, 0));
        Unmortgage.setText("Unmortgage");
        jPanel1.add(Unmortgage);
        Unmortgage.setBounds(320, 200, 160, 50);

        MortgageButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        MortgageButton.setForeground(new java.awt.Color(0, 0, 0));
        MortgageButton.setText("Mortgage");
        jPanel1.add(MortgageButton);
        MortgageButton.setBounds(60, 200, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MortgageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MortgageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MortgageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MortgageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MortgageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton MortgageButton;
    public javax.swing.JComboBox<String> PropertiesComboBox;
    public javax.swing.JButton Unmortgage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
