/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ClientView;

import Model.Game.Property;
import java.awt.Color;

/**
 *
 * @author nacho
 */
public class PropertyView extends javax.swing.JFrame {

    /**
     * Creates new form PropertyView
     */
    public PropertyView(Property property) {
        initComponents();
        setSize(445,585);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ColorPanel.setBackground(property.getColor());
        DeedNameLabel.setText(property.getName());
        RentPriceLabel.setText("$ "+property.getPrice());
        House1PriceLabel.setText("$ "+property.getPrice()*2);
        House2PriceLabel.setText("$ "+property.getPrice()*3);
        House3PriceLabel.setText("$ "+property.getPrice()*4);
        House4PriceLabel.setText("$ "+property.getPrice()*5);
        HotelPriceLabel.setText("$ "+property.getPrice()*6);
        MortgageValueLabel.setText("$ "+property.getMortagePrice());
        HouseValueLabel.setText("$ "+property.getBuildingPrice());
        HotelValueLabel.setText("$ "+property.getBuildingPrice());
        
        if(property.getOwner() == null)
            OwnerNameLabel.setText("FREE");
        else
            OwnerNameLabel.setText(property.getOwner().name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ColorPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DeedNameLabel = new javax.swing.JLabel();
        RentLabel = new javax.swing.JLabel();
        RentPriceLabel = new javax.swing.JLabel();
        House4Label = new javax.swing.JLabel();
        House1Label = new javax.swing.JLabel();
        House2Label = new javax.swing.JLabel();
        House3Label = new javax.swing.JLabel();
        OwnerLabel = new javax.swing.JLabel();
        HouseValueLabel = new javax.swing.JLabel();
        House1PriceLabel = new javax.swing.JLabel();
        House2PriceLabel = new javax.swing.JLabel();
        House3PriceLabel = new javax.swing.JLabel();
        House4PriceLabel = new javax.swing.JLabel();
        MortgageLabel = new javax.swing.JLabel();
        OwnerNameLabel = new javax.swing.JLabel();
        HousesCostLabel = new javax.swing.JLabel();
        MortgageValueLabel = new javax.swing.JLabel();
        HotelCostLabel = new javax.swing.JLabel();
        HotelValueLabel = new javax.swing.JLabel();
        HotelLabel = new javax.swing.JLabel();
        HotelPriceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);

        ColorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        ColorPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("TITLE DEED");
        ColorPanel.add(jLabel1);
        jLabel1.setBounds(140, 20, 150, 16);

        DeedNameLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        DeedNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeedNameLabel.setText("TENNESSEE AVE.");
        ColorPanel.add(DeedNameLabel);
        DeedNameLabel.setBounds(20, 40, 350, 40);

        jPanel2.add(ColorPanel);
        ColorPanel.setBounds(10, 10, 390, 90);

        RentLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        RentLabel.setForeground(new java.awt.Color(0, 0, 0));
        RentLabel.setText("RENT");
        jPanel2.add(RentLabel);
        RentLabel.setBounds(160, 110, 41, 40);

        RentPriceLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        RentPriceLabel.setForeground(new java.awt.Color(0, 0, 0));
        RentPriceLabel.setText("$ 14");
        jPanel2.add(RentPriceLabel);
        RentPriceLabel.setBounds(210, 110, 90, 40);

        House4Label.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        House4Label.setForeground(new java.awt.Color(0, 0, 0));
        House4Label.setText("With 4 Houses");
        jPanel2.add(House4Label);
        House4Label.setBounds(40, 270, 150, 40);

        House1Label.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        House1Label.setForeground(new java.awt.Color(0, 0, 0));
        House1Label.setText("With 1 House");
        jPanel2.add(House1Label);
        House1Label.setBounds(40, 150, 150, 40);

        House2Label.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        House2Label.setForeground(new java.awt.Color(0, 0, 0));
        House2Label.setText("With 2 Houses");
        jPanel2.add(House2Label);
        House2Label.setBounds(40, 190, 150, 40);

        House3Label.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        House3Label.setForeground(new java.awt.Color(0, 0, 0));
        House3Label.setText("With 3 Houses");
        jPanel2.add(House3Label);
        House3Label.setBounds(40, 230, 150, 40);

        OwnerLabel.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        OwnerLabel.setForeground(new java.awt.Color(0, 0, 0));
        OwnerLabel.setText("OWNER: ");
        jPanel2.add(OwnerLabel);
        OwnerLabel.setBounds(100, 440, 120, 40);

        HouseValueLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        HouseValueLabel.setForeground(new java.awt.Color(0, 0, 0));
        HouseValueLabel.setText("$ 100");
        jPanel2.add(HouseValueLabel);
        HouseValueLabel.setBounds(220, 370, 90, 40);

        House1PriceLabel.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        House1PriceLabel.setForeground(new java.awt.Color(0, 0, 0));
        House1PriceLabel.setText("$ 70");
        jPanel2.add(House1PriceLabel);
        House1PriceLabel.setBounds(310, 150, 90, 40);

        House2PriceLabel.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        House2PriceLabel.setForeground(new java.awt.Color(0, 0, 0));
        House2PriceLabel.setText("$ 200");
        jPanel2.add(House2PriceLabel);
        House2PriceLabel.setBounds(310, 190, 90, 40);

        House3PriceLabel.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        House3PriceLabel.setForeground(new java.awt.Color(0, 0, 0));
        House3PriceLabel.setText("$ 550");
        jPanel2.add(House3PriceLabel);
        House3PriceLabel.setBounds(310, 230, 90, 40);

        House4PriceLabel.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        House4PriceLabel.setForeground(new java.awt.Color(0, 0, 0));
        House4PriceLabel.setText("$ 750");
        jPanel2.add(House4PriceLabel);
        House4PriceLabel.setBounds(310, 270, 90, 40);

        MortgageLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        MortgageLabel.setForeground(new java.awt.Color(0, 0, 0));
        MortgageLabel.setText("Mortgage Value");
        jPanel2.add(MortgageLabel);
        MortgageLabel.setBounds(100, 340, 110, 40);

        OwnerNameLabel.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        OwnerNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        OwnerNameLabel.setText("FREE");
        jPanel2.add(OwnerNameLabel);
        OwnerNameLabel.setBounds(200, 440, 90, 40);

        HousesCostLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        HousesCostLabel.setForeground(new java.awt.Color(0, 0, 0));
        HousesCostLabel.setText("Houses cost");
        jPanel2.add(HousesCostLabel);
        HousesCostLabel.setBounds(100, 370, 100, 40);

        MortgageValueLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        MortgageValueLabel.setForeground(new java.awt.Color(0, 0, 0));
        MortgageValueLabel.setText("$ 90");
        jPanel2.add(MortgageValueLabel);
        MortgageValueLabel.setBounds(220, 340, 90, 40);

        HotelCostLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        HotelCostLabel.setForeground(new java.awt.Color(0, 0, 0));
        HotelCostLabel.setText("Hotel cost");
        jPanel2.add(HotelCostLabel);
        HotelCostLabel.setBounds(100, 400, 100, 40);

        HotelValueLabel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        HotelValueLabel.setForeground(new java.awt.Color(0, 0, 0));
        HotelValueLabel.setText("$ 100");
        jPanel2.add(HotelValueLabel);
        HotelValueLabel.setBounds(220, 400, 90, 40);

        HotelLabel.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        HotelLabel.setForeground(new java.awt.Color(0, 0, 0));
        HotelLabel.setText("With HOTEL");
        jPanel2.add(HotelLabel);
        HotelLabel.setBounds(100, 310, 120, 40);

        HotelPriceLabel.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        HotelPriceLabel.setForeground(new java.awt.Color(0, 0, 0));
        HotelPriceLabel.setText("$  950");
        jPanel2.add(HotelPriceLabel);
        HotelPriceLabel.setBounds(220, 310, 90, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 410, 530);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PropertyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PropertyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PropertyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PropertyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PropertyView(new Property(Color.PINK,"St. Charles Place",10,100,70,140)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel ColorPanel;
    public javax.swing.JLabel DeedNameLabel;
    private javax.swing.JLabel HotelCostLabel;
    private javax.swing.JLabel HotelLabel;
    public javax.swing.JLabel HotelPriceLabel;
    public javax.swing.JLabel HotelValueLabel;
    private javax.swing.JLabel House1Label;
    public javax.swing.JLabel House1PriceLabel;
    private javax.swing.JLabel House2Label;
    public javax.swing.JLabel House2PriceLabel;
    private javax.swing.JLabel House3Label;
    public javax.swing.JLabel House3PriceLabel;
    private javax.swing.JLabel House4Label;
    public javax.swing.JLabel House4PriceLabel;
    public javax.swing.JLabel HouseValueLabel;
    private javax.swing.JLabel HousesCostLabel;
    private javax.swing.JLabel MortgageLabel;
    public javax.swing.JLabel MortgageValueLabel;
    private javax.swing.JLabel OwnerLabel;
    public javax.swing.JLabel OwnerNameLabel;
    private javax.swing.JLabel RentLabel;
    private javax.swing.JLabel RentPriceLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
