/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ClientView;

/**
 *
 * @author nacho
 */
public class RollDiceWindow extends javax.swing.JFrame {

    /**
     * Creates new form RollDiceWindow
     */
    public RollDiceWindow() {
        initComponents();
        setSize(270,250);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        DicesButton = new javax.swing.JButton();
        Dice1Label = new javax.swing.JLabel();
        Dice2Label = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(164, 208, 167));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(164, 208, 167));
        jPanel1.setLayout(null);

        TitleLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        TitleLabel.setText("Roll the dices ");
        jPanel1.add(TitleLabel);
        TitleLabel.setBounds(10, 10, 150, 40);

        DicesButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        DicesButton.setText("Roll");
        DicesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DicesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DicesButton);
        DicesButton.setBounds(90, 150, 78, 32);

        Dice1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Red1.jpg"))); // NOI18N
        jPanel1.add(Dice1Label);
        Dice1Label.setBounds(30, 60, 63, 63);

        Dice2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Red1.jpg"))); // NOI18N
        jPanel1.add(Dice2Label);
        Dice2Label.setBounds(160, 60, 60, 63);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DicesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DicesButtonActionPerformed
        
    }//GEN-LAST:event_DicesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RollDiceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RollDiceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RollDiceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RollDiceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RollDiceWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Dice1Label;
    public javax.swing.JLabel Dice2Label;
    public javax.swing.JButton DicesButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
