/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ClientView;

/**
 *
 * @author nacho
 */
public class SellView extends javax.swing.JFrame {

    /**
     * Creates new form SellView
     */
    public SellView(String[] properties,String[] players) {
        initComponents();
        setSize(749,440);
        PropertiesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(properties));
        PlayerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(players));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SellEdificarionsButton = new javax.swing.JButton();
        SellToBankButton = new javax.swing.JButton();
        SellToPlayer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SellPriceSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        PropertiesComboBox = new javax.swing.JComboBox<>();
        PlayerComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(164, 208, 167));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SELL A PROPERTY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 20, 290, 60);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Propertie's name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 120, 190, 30);

        SellEdificarionsButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        SellEdificarionsButton.setText("Sell Edifications");
        jPanel1.add(SellEdificarionsButton);
        SellEdificarionsButton.setBounds(430, 300, 200, 50);

        SellToBankButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        SellToBankButton.setText("Sell to Bank");
        jPanel1.add(SellToBankButton);
        SellToBankButton.setBounds(430, 110, 200, 50);

        SellToPlayer.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        SellToPlayer.setText("Sell to a Player");
        jPanel1.add(SellToPlayer);
        SellToPlayer.setBounds(430, 200, 200, 50);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Player to sell Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 220, 210, 40);

        SellPriceSpinner.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(SellPriceSpinner);
        SellPriceSpinner.setBounds(80, 350, 80, 32);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sell Price");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 320, 100, 26);

        PropertiesComboBox.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        PropertiesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(PropertiesComboBox);
        PropertiesComboBox.setBounds(20, 160, 220, 40);

        PlayerComboBox.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        PlayerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(PlayerComboBox);
        PlayerComboBox.setBounds(20, 260, 220, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellView(new String[]{},new String[]{}).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> PlayerComboBox;
    public javax.swing.JComboBox<String> PropertiesComboBox;
    public javax.swing.JButton SellEdificarionsButton;
    public javax.swing.JSpinner SellPriceSpinner;
    public javax.swing.JButton SellToBankButton;
    public javax.swing.JButton SellToPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
