/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ClientView;

import Model.Game.Property;

/**
 *
 * @author nacho
 */
public class ServiceView extends javax.swing.JFrame {

    /**
     * Creates new form ServiceView
     */
    public ServiceView(Property card) {
        initComponents();
        setSize(445,585);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        ServiceNameLabel.setText(card.getName());
        
        if(card.getOwner() != null){
            OwnerNameLabel.setText(card.getOwner().name);
        }
        
        if (card.getName().equals("Water Works"))
            ServiceImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WaterServiceLogo.jpg")));
        else
            ServiceImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ElectrcServiceLogo.jpg")));
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ServiceImageLabel = new javax.swing.JLabel();
        ServiceNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        OwnerNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);

        ServiceImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ElectrcServiceLogo.jpg"))); // NOI18N
        jPanel2.add(ServiceImageLabel);
        ServiceImageLabel.setBounds(130, 30, 150, 170);

        ServiceNameLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        ServiceNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        ServiceNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ServiceNameLabel.setText("ELECTRIC COMPANY");
        jPanel2.add(ServiceNameLabel);
        ServiceNameLabel.setBounds(50, 210, 320, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("If one Utility is owned ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(120, 280, 180, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("rent is 4 times amount ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(120, 300, 190, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("shown on dice");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(150, 320, 120, 16);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("If both Utilities are owned,");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 370, 220, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("rent is 10 times amount");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(110, 390, 190, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("shown on dice");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(140, 410, 120, 16);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Owner: ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 480, 90, 30);

        OwnerNameLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        OwnerNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        OwnerNameLabel.setText("FREE");
        jPanel2.add(OwnerNameLabel);
        OwnerNameLabel.setBounds(130, 480, 80, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 410, 530);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OwnerNameLabel;
    private javax.swing.JLabel ServiceImageLabel;
    private javax.swing.JLabel ServiceNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
